/* tslint:disable */
/* eslint-disable */
/**
 * IONOS DBaaS MariaDB REST API
 * An enterprise-grade Database is provided as a Service (DBaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.  The API allows you to create additional MariaDB database clusters or modify existing ones. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BaseBackup } from './base-backup';

/**
 * A backup object.
 * @export
 * @interface Backup
 */
export interface Backup {

    /**
     * The unique ID of the cluster that was backed up.
     * @type {string}
     * @memberof Backup
     */
    clusterId?: string;

    /**
     * The oldest available timestamp to which you can restore.
     * @type {string}
     * @memberof Backup
     */
    earliestRecoveryTargetTime?: string;

    /**
     * Size of all base backups in MiB. This is at least the sum of all base backup sizes. 
     * @type {number}
     * @memberof Backup
     */
    size?: number;

    /**
     * 
     * @type {Array<BaseBackup>}
     * @memberof Backup
     */
    baseBackups?: Array<BaseBackup>;
}


