/* tslint:disable */
/* eslint-disable */
/**
 * IONOS DBaaS MariaDB REST API
 * An enterprise-grade Database is provided as a Service (DBaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.  The API allows you to create additional MariaDB database clusters or modify existing ones. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Connection } from './connection';
import { MaintenanceWindow } from './maintenance-window';
import { MariadbVersion } from './mariadb-version';

/**
 * Properties of a database cluster.
 * @export
 * @interface ClusterProperties
 */
export interface ClusterProperties {

    /**
     * The friendly name of your cluster.
     * @type {string}
     * @memberof ClusterProperties
     */
    displayName?: string;

    /**
     * 
     * @type {MariadbVersion}
     * @memberof ClusterProperties
     */
    mariadbVersion?: MariadbVersion;

    /**
     * The DNS name pointing to your cluster.
     * @type {string}
     * @memberof ClusterProperties
     */
    dnsName?: string;

    /**
     * The total number of instances in the cluster (one primary and n-1 secondary). 
     * @type {number}
     * @memberof ClusterProperties
     */
    instances?: number;

    /**
     * The amount of memory per instance in gigabytes (GB).
     * @type {number}
     * @memberof ClusterProperties
     */
    ram?: number;

    /**
     * The number of CPU cores per instance.
     * @type {number}
     * @memberof ClusterProperties
     */
    cores?: number;

    /**
     * The amount of storage per instance in gigabytes (GB).
     * @type {number}
     * @memberof ClusterProperties
     */
    storageSize?: number;

    /**
     * 
     * @type {Array<Connection>}
     * @memberof ClusterProperties
     */
    connections?: Array<Connection>;

    /**
     * 
     * @type {MaintenanceWindow}
     * @memberof ClusterProperties
     */
    maintenanceWindow?: MaintenanceWindow;
}


